import { Gift } from './gift';

export const GIFTS: Gift[] = [
  {
      "id":11,
      "brand":"Disney+",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Disney%2B_logo.svg/1000px-Disney%2B_logo.svg.png",
      "recipient":"mother",
      "name":"National Geographic Channel",
      "type":"Digital Subscription",
      "url":"https://i.ytimg.com/vi/BHgo3oB0A5Q/hqdefault.jpg",
      "description":"Watch full episodes, specials and documentaries with National Geographic TV channel online.",
      "package":"",
      "price":"$12 - $120"
   },
   {
      "id":11,
      "brand":"Disney+",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Disney%2B_logo.svg/1000px-Disney%2B_logo.svg.png",
      "recipient":"brother",
      "name":"Marvel Franchise Streaming Subscription",
      "type":"Digital Subscription",
      "url":"https://cdn.images.express.co.uk/img/dynamic/36/590x/Ant-Man-and-the-Wasp-Netflix-disney-streaming-last-Marvel-movie-1000683.jpg?r=1533735893712",
      "description":"",
      "package":"",
      "price":"$12 - $120"
   },
   {
      "id":11,
      "brand":"Youtube",
      "brandlogoUrl":"https://logos-world.net/wp-content/uploads/2020/04/YouTube-Emblem.png",
      "recipient":"brother",
      "name":"Ad Free Youtube Experience",
      "type":"Digital Subscription",
      "url":"https://www.cnet.com/a/img/a0FFE0VNinTZqaHael9X2b5czFc=/1200x675/2020/01/01/301595b2-19b5-4399-94a2-718b3e3ed15c/youtube-logo-laptop-4692.jpg",
      "description":"Get your youtube obsessed giftee a premium account so they dont have to watch endless ads",
      "package":"",
      "price":"$12 - $180"
   },
   {
      "id":13,
      "description":"Welcome to the Wine Lovers Subscription box – created by wine lovers for wine lovers who want to treat themselves and their loved ones to new wine and yummy treats. Each Box contains 2 full bottles of premium wine, delicious gourmet treats as well as tasting and food pairing notes. ",
      "package":"",
      "price":"$50 - $600",
      "brand":"Cratejoy",
      "brandlogoUrl":"https://sell.cratejoy.com/wp-content/uploads/2016/07/logo-gray.png",
      "recipient":"mother",
      "name":"Wine Subscription",
      "type":"Physical Subscription",
      "url":"https://sell.cratejoy.com/wp-content/uploads/2016/04/wine-subscription-box-815x611.jpg"
   },
   {
      "id":13,
      "description":"Enjoy your fast-track to becoming a Grill Master! Receive a monthly delivery of the best grilling and BBQ goods and supplies hand-selected by a certified BBQ pitmaster. We take the time to research, taste test, and vet every supplier we work with to guarantee you the best grilling experience. Experiment with new sauces, rubs, tools, and more!",
      "package":"",
      "price":"$25 - $300",
      "brand":"Cratejoy",
      "brandlogoUrl":"https://sell.cratejoy.com/wp-content/uploads/2016/07/logo-gray.png",
      "recipient":"brother",
      "name":"Grill Master Club",
      "type":"Physical Subscription",
      "url":"https://cdn.filestackcontent.com/auto_image/cache=expiry:max/vQqGlJToQBit02SVD1uJ"
   },
   {
      "id":14,
      "description":"The Dapper Dog subscription box is the only box that sends you a gorgeous, limited edition bandana every month! These high-quality dog bandanas are available exclusively from Dapper Dog. Each box also includes 2 healthy bags of treats or chews and 2 adorable toys, all curated around cute themes like Fun in the Sun, Under the Sea, and Happy Howlidays.",
      "package":"",
      "price":"$35 - $380",
      "brand":"Dapper Dog",
      "brandlogoUrl":"https://cdn.shopify.com/s/files/1/0112/2110/6750/products/dapper-dog-gift-card-355391_1024x1024.jpg?v=1597594744",
      "recipient":"sister",
      "name":"Dog Food Subscription",
      "type":"Physical Subscription",
      "url":"https://cdn.filestackcontent.com/auto_image/cache=expiry:max/vYjkMYyIQvGgHyQ82cSk"
   },
   {
      "id":15,
      "description":"A subscription box for people who love handmade soap. My soaps are great for the skin, smell amazing and are pretty to look at. Made with a short list of ingredients (that you can pronounce), my bars range from scrubby and exfoliating to creamy and silky.",
      "package":"",
      "price":"$10 - $120",
      "brand":"Cratejoy",
      "brandlogoUrl":"https://sell.cratejoy.com/wp-content/uploads/2016/07/logo-gray.png",
      "recipient":"mother",
      "name":"Soap Subscription",
      "type":"Physical Subscription",
      "url":"https://cdn.filestackcontent.com/auto_image/cache=expiry:max/UmAGhWJSTNy17rzdfIoz"
   },
   {
      "id":16,
      "description":"CuriosityStream has thousands of documentaries that enlighten, entertain & inspire",
      "package":"",
      "price":"$3 - $60",
      "brand":"Curiosity Stream",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/CuriosityStreamBlack.svg/1200px-CuriosityStreamBlack.svg.png",
      "recipient":"brother",
      "name":"Documentary Streaming Subscription",
      "type":"Digital Subscription",
      "url":"https://www.soda.com/wp-content/uploads/2020/08/CuriosityStream-Review.png"
   },
   {
      "id":17,
      "description":"Live a healthier, happier, more well-rested life in just a few minutes a day with the Headspace app.",
      "package":"",
      "price":"$20 - $90",
      "brand":"Headspace",
      "brandlogoUrl":"https://180dc.org/wp-content/uploads/2019/05/headspace-app-logo-fitted-900x754.jpg",
      "recipient":"mother",
      "name":"Meditation App Subscription",
      "type":"Membership",
      "url":"https://www.boldbusiness.com/wp-content/uploads/2019/04/Feature-Image-8.jpg"
   },
   {
      "id":18,
      "description":"A pass is your ticket to more than 2,000 federal recreation sites. Each pass covers entrance fees at national parks and national wildlife refuges as well as standard amenity fees (day use fees) at national forests and grasslands, and at lands managed by the Bureau of Land Management, Bureau of Reclamation and U.S. Army Corps of Engineers.",
      "package":"",
      "price":"$80",
      "brand":"National Parks",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/US-NationalParkService-Logo.svg/1200px-US-NationalParkService-Logo.svg.png",
      "recipient":"mother",
      "name":"Park Pass",
      "type":"Membership",
      "url":"https://store.usgs.gov/s3fs-public/2021AnnualPass.png"
   },
   {
      "id":12,
      "description":"Whether you rock 'em on wall street or to wal mart, these comfortable chinos will have you looking stylish and feeling comfortable",
      "package":"",
      "price":"",
      "brand":"LuLuLemon",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Lululemon_Athletica_logo.svg/1200px-Lululemon_Athletica_logo.svg.png",
      "recipient":"brother",
      "name":"Gift Card",
      "type":"Gift Card",
      "url":"https://pyxis.nymag.com/v1/imgs/68d/41c/779b791343d53fde78656af60fa122d97a-31-pants-ode.rhorizontal.w700.jpg"
   },
   {
      "id":19,
      "description":"Thomas Keller has won more Michelin stars than any chef in America. In his first online cooking class, the founder of The French Laundry and Per Se teaches you the underlying techniques of making great food so you can go beyond the cookbook. ",
      "package":"",
      "price":"$20 - $240",
      "brand":"Masterclass",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Masterclass_logo.svg/800px-Masterclass_logo.svg.png",
      "recipient":"sister",
      "name":"Thomas Keller - Cooking techniques ",
      "type":"Digital Subscription",
      "url":"https://www.masterclass.com/course-images/attachments/A5mJ6Qd5pRhrkmS2BWUpUf8X"
   },
   {
      "id":19,
      "description":"Subscribe and rent any 6 styles, every month. What's included: fast, free shipping + returns. What's not: hidden fees. What else? You can pause or cancel anytime. ",
      "package":"",
      "price":"$88 - $1000",
      "brand":"Nuuly",
      "brandlogoUrl":"https://www.nuuly.com/static/logo_630x630.png",
      "recipient":"sister",
      "name":"Online Clothing Rental",
      "type":"Physical Subscription",
      "url":"https://media.greenmatters.com/brand-img/o6eTfo-8V/0x0/nuuly-free-people-anthropologie-1558539202663.jpg"
   },
   {
      "id":19,
      "description":"Need a gift for the happy couple? How about a joke for that best man speech? Or even getting your bestie that something “new”—we got the stars just for that.",
      "package":"",
      "price":"$200",
      "brand":"Celebrity Cameo",
      "brandlogoUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Cameo-Logo.png/1200px-Cameo-Logo.png",
      "recipient":"sister",
      "name":"Worlds Most Interesting Man",
      "type":"Other",
      "url":"https://ssl-static.libsyn.com/p/assets/f/3/a/2/f3a203d0a310cbfd/most-interesting-man-goldsmith-1504044751.jpg"
   }
 ]; 